### ISSUE TITLE
[BUG]玩家登录服务器时报错，不能正常进入服务器

### ISSUE THREAD

**Issue by rainbowbedrock** [GHAuth-Team/ghauth#11]
**Describe the bug**
玩家登录服务器时ghauth报错，不返回数据导致玩家无法登录。在启动器登录时正常。

0|ghauth  | ReferenceError: textureData is not defined
0|ghauth  |     at Object.genUserProfile (/srv/ghauth/service/user.js:295:34)
0|ghauth  |     at /srv/ghauth/service/token.js:278:37
0|ghauth  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)

**To Reproduce**
玩家登录服务器

**Expected behavior**
完成验证并让玩家登录服务器

服务器操作系统 Arch Linux
node版本 14.16.0 和 16.3.0 均出现此问题
ghauth版本 release中的 v0.5.1 和 main分支最新代码均有此问题

**Comment by rainbowbedrock** [comment]
找到原因并修复了一下，已经提交pr #12

**Comment by daidr** [comment]
首先非常感谢您的pr，不过该问题已经在dev分支内得到修复，会在下一次版本更新时合并到主分支，所以我只能关闭您所提交的pr，非常抱歉。
